# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Coding\Blackjack_C

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Coding\Blackjack_C

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Coding\Blackjack_C\CMakeFiles D:\Coding\Blackjack_C\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Coding\Blackjack_C\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cards

# Build rule for target.
Cards: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Cards
.PHONY : Cards

# fast build rule for target.
Cards/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Cards.dir\build.make CMakeFiles/Cards.dir/build
.PHONY : Cards/fast

#=============================================================================
# Target rules for targets named LinkedList

# Build rule for target.
LinkedList: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 LinkedList
.PHONY : LinkedList

# fast build rule for target.
LinkedList/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LinkedList.dir\build.make CMakeFiles/LinkedList.dir/build
.PHONY : LinkedList/fast

#=============================================================================
# Target rules for targets named Player

# Build rule for target.
Player: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Player
.PHONY : Player

# fast build rule for target.
Player/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Player.dir\build.make CMakeFiles/Player.dir/build
.PHONY : Player/fast

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Game.dir\build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

cards.obj: cards.c.obj
.PHONY : cards.obj

# target to build an object file
cards.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Cards.dir\build.make CMakeFiles/Cards.dir/cards.c.obj
.PHONY : cards.c.obj

cards.i: cards.c.i
.PHONY : cards.i

# target to preprocess a source file
cards.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Cards.dir\build.make CMakeFiles/Cards.dir/cards.c.i
.PHONY : cards.c.i

cards.s: cards.c.s
.PHONY : cards.s

# target to generate assembly for a file
cards.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Cards.dir\build.make CMakeFiles/Cards.dir/cards.c.s
.PHONY : cards.c.s

game.obj: game.c.obj
.PHONY : game.obj

# target to build an object file
game.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Game.dir\build.make CMakeFiles/Game.dir/game.c.obj
.PHONY : game.c.obj

game.i: game.c.i
.PHONY : game.i

# target to preprocess a source file
game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Game.dir\build.make CMakeFiles/Game.dir/game.c.i
.PHONY : game.c.i

game.s: game.c.s
.PHONY : game.s

# target to generate assembly for a file
game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Game.dir\build.make CMakeFiles/Game.dir/game.c.s
.PHONY : game.c.s

linked_list.obj: linked_list.c.obj
.PHONY : linked_list.obj

# target to build an object file
linked_list.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LinkedList.dir\build.make CMakeFiles/LinkedList.dir/linked_list.c.obj
.PHONY : linked_list.c.obj

linked_list.i: linked_list.c.i
.PHONY : linked_list.i

# target to preprocess a source file
linked_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LinkedList.dir\build.make CMakeFiles/LinkedList.dir/linked_list.c.i
.PHONY : linked_list.c.i

linked_list.s: linked_list.c.s
.PHONY : linked_list.s

# target to generate assembly for a file
linked_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\LinkedList.dir\build.make CMakeFiles/LinkedList.dir/linked_list.c.s
.PHONY : linked_list.c.s

player.obj: player.c.obj
.PHONY : player.obj

# target to build an object file
player.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Player.dir\build.make CMakeFiles/Player.dir/player.c.obj
.PHONY : player.c.obj

player.i: player.c.i
.PHONY : player.i

# target to preprocess a source file
player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Player.dir\build.make CMakeFiles/Player.dir/player.c.i
.PHONY : player.c.i

player.s: player.c.s
.PHONY : player.s

# target to generate assembly for a file
player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Player.dir\build.make CMakeFiles/Player.dir/player.c.s
.PHONY : player.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Cards
	@echo ... Game
	@echo ... LinkedList
	@echo ... Player
	@echo ... cards.obj
	@echo ... cards.i
	@echo ... cards.s
	@echo ... game.obj
	@echo ... game.i
	@echo ... game.s
	@echo ... linked_list.obj
	@echo ... linked_list.i
	@echo ... linked_list.s
	@echo ... player.obj
	@echo ... player.i
	@echo ... player.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

